---
# tasks file for go_install

# Debian
- block:

  - ansible.builtin.include_role:
      name: fruafr.linux.snapd_install

  when: ansible_os_family == 'Debian'

#Install go language
#https://snapcraft.io/go

- name: 'go --classic should be present'
  become: true
  community.general.snap:
    name: go
    classic: true
    state: present

