---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for go_install

# Install go language

# Debian
- block:

  - ansible.builtin.include_role:
      name: fruafr.linux.packages_snapd

  when: ansible_os_family == 'Debian'

#Install go language
#https://snapcraft.io/go

- name: 'go --classic should be present'
  become: true
  community.general.snap:
    name: go
    classic: true
    state: present

