---
# tasks file for scm_git_install

# Debian
- block:

  - name: 'Check if git is installed'
    become: true
    command: "dpkg-query -W git"
    register: package
    failed_when: package.rc > 1
    changed_when: package.rc == 1

  - block:
    # sudo apt-get install git
    - name: 'DEBIAN - git SCM package'
      become: true
      ansible.builtin.apt:
        pkg:
          - git
        state: latest
    when: package.rc == 1

  when: ansible_os_family == 'Debian'

