---
# tasks file for ccpp_install

# Debian
- block:
  # sudo apt-get install build-essential libssl-dev ccache ...
  # https://www.tecmint.com/install-c-compiler-and-development-build-essential-tools-in-debian-ubuntu/
  - name: 'DEBIAN - C/C++ development libraries : build-essential, libssl-dev, ccache ...'
    become: true
    ansible.builtin.apt:
      pkg:
        - build-essential
        - libssl-dev
        - ccache
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils 
        - tk-dev
      state: latest
  when: ansible_os_family == 'Debian'
