---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# Install PHP (Common, CLI + Pear)
# https://www.php.net/manual/en/install.unix.debian.php
- hosts: all
  collections:
    - fruafr.dev
  roles:
    - php_install