---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for nodejs_test

# Test node.js install

# Test node
- shell: node -v
  register: version

- name: 'node -v'
  debug: var=version.stdout_lines

# Test yarn
- shell: yarn --version
  register: yarn_version

- name: 'yarn --version'
  debug: var=yarn_version.stdout_lines