---
# tasks file for python3_install

# Debian
- block:
  #sudo apt-get -y install python3 python3-pip python3-setuptools virtualenv python3-venv python3-virtualenv
    - name: DEBIAN - Install Python3 and pip
      become: true
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-pip
          - python3-setuptools
          - virtualenv
          - python3-venv
          - python3-virtualenv
        state: latest
        update_cache: true
  when: ansible_os_family == 'Debian'
