---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for java_jre_test

# Test Java Runtime Environment (JRE) install

#Check java version
- shell: java -version
  register: jreversion

- name: java version
  debug: var=jreversion.stderr_lines